apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-source-workspace
  labels:
    region: us-east
    zone: wdc07
spec:
  storageClassName: "{{DEFAULT_BLOCK_STORAGE}}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildah-mq
  labels:
    region: us-east
    zone: wdc07
spec:
  storageClassName: "{{DEFAULT_BLOCK_STORAGE}}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildah-ace-api
  labels:
    region: us-east
    zone: wdc07
spec:
  storageClassName: "{{DEFAULT_BLOCK_STORAGE}}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildah-ace-acme
  labels:
    region: us-east
    zone: wdc07
spec:
  storageClassName: "{{DEFAULT_BLOCK_STORAGE}}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildah-ace-bernie
  labels:
    region: us-east
    zone: wdc07
spec:
  storageClassName: "{{DEFAULT_BLOCK_STORAGE}}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildah-ace-chris
  labels:
    region: us-east
    zone: wdc07
spec:
  storageClassName: "{{DEFAULT_BLOCK_STORAGE}}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
